variable "target_project_id" {
  description = "GCP project that owns the task dataset"
  type        = string
}

variable "task_id" {
  description = "Legacy portal task identifier"
  type        = string
}

variable "task_name" {
  description = "Legacy portal task name"
  type        = string
}

variable "group" {
  description = "Task group code, for example a/b/c"
  type        = string
}

variable "dataset_id" {
  description = "BigQuery dataset ID generated by the Cloud Run adapter"
  type        = string
}

variable "bq_location" {
  description = "BigQuery dataset location"
  type        = string
  default     = "asia-northeast3"
}

variable "gke_project_id" {
  description = "GCP project that owns the GKE cluster; empty means target_project_id"
  type        = string
  default     = ""
}

variable "gke_cluster_name" {
  description = "Existing GKE Autopilot cluster used by analysis tasks"
  type        = string
  default     = "analysis-autopilot-a"
}

variable "gke_location" {
  description = "Region or zone of the GKE cluster"
  type        = string
  default     = "asia-northeast3"
}
