variable "target_project_id" {
  description = "GCP project that owns the task dataset"
  type        = string
}

variable "task_id" {
  description = "Legacy portal task identifier"
  type        = string
}

variable "task_name" {
  description = "Legacy portal task name"
  type        = string
}

variable "group" {
  description = "Task group code, for example a/b/c"
  type        = string
}

variable "dataset_id" {
  description = "BigQuery dataset ID generated by the Cloud Run adapter"
  type        = string
}

variable "bq_location" {
  description = "BigQuery dataset location"
  type        = string
  default     = "asia-northeast3"
}
